[package]
name = "tokenomicon"
version = "0.1.0"
authors = ["Artem Sergeev <...>"]
edition = "2021"

[dependencies]
log = "0.4.25"
axum = "0.8.1"
config = "0.15.7"
anyhow = "1.0.95"
serde_json = "1.0.138"
unicode-segmentation = "1.12.0"
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
